name: Deploy GitHub Pages

# Se ejecuta al hacer push a main
on:
  push:
    branches:
      - main

# Permisos necesarios para GitHub Pages y OIDC
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
